### ISSUE TITLE
Consider using `git submodule`

### ISSUE THREAD

**Issue by skulumani** [fdcl-gwu/fdcl_serialization#1]
Consider using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to manage libraries/directories that are shared across repositories.

Currently the following all use the `eigen` library by having a local copy of the source

* [fdcl-gwu/Filter_Pthread](https://github.com/fdcl-gwu/Filter_Pthread)
* [fdcl-gwu/fdcl_param](https://github.com/fdcl-gwu/fdcl_param)
* [fdcl-gwu/fdcl_serialization](https://github.com/fdcl-gwu/fdcl_serialization)

Instead one can use a single `eigen` module (hosted by us) and use a submodule in each repository.

Also, another idea is to simply 'install' eigen in a central location, for use by all applications on the system. This would alleviate any issues with having different results from different versions of the library.

**Comment by kanishkegb** [comment]
implemented in [d2b03aef7fccc9697db147df77b23ce07619c1ed](https://github.com/fdcl-gwu/fdcl_serialization/commit/d2b03aef7fccc9697db147df77b23ce07619c1ed)
